### ISSUE TITLE
Code protection

### ISSUE THREAD

**Issue by johnrobledo** [ImSorryButWho/HomeAssistantNotes#1]
How to make it only disarm the alarm when a specific code is inputted?

**Comment by ImSorryButWho** [comment]
The alarm component in Home Assistant (either the built-in Alarm Panel, or a third-party replacement like Alarmo) controls the logic, not the keypad.  I don't have a full write-up of how to set up Alarmo, but [the outside-Alarmo automations](https://github.com/ImSorryButWho/HomeAssistantNotes/blob/main/alarm_keypad_automations.yaml) and an example of the [inside Alarmo actions](https://github.com/ImSorryButWho/HomeAssistantNotes/blob/main/alarmo_automation.png) should give a reasonable idea of how to integrate it.

As far as requiring a code to disarm, be sure that "Use disarm code" is turned on in Alarmo's codes screen.

**Comment by ImSorryButWho** [comment]
Sure, you could add `event_data: '1234'` to the `event_data` section of the trigger to match only on that code.   See the [Automation Trigger](https://www.home-assistant.io/docs/automation/trigger/#event-trigger) docs for details.  That said, I still don't think I understand what you're trying to accomplish.

You (should!) already have the alarm configured to recognize the correct code.  Doing additional filtering at this point makes it easier to accidentally expose your code (since it's sitting there in plain text in your `automations.yaml`), and doesn't add any extra security.

**Comment by ImSorryButWho** [comment]
That's what the template in the automation above is doing.  When the automation is run, `{{ trigger.event.data.event_data }}` will be replaced by the `event_data` field in the data from the event that was the trigger for the automation that was run.  That is, the code that the user entered.  See the [templating docs](https://www.home-assistant.io/docs/configuration/templating/) for more than you ever wanted to know about templates.

**Comment by johnrobledo** [comment]
Thank you soooo much! It worked.....i wasn;t fully understanding it that
the code entered into the keypad pertained to the pin set in lovelace

**Comment by johnrobledo** [comment]
Also, I am sorry for being so difficult!
