### ISSUE TITLE
Night mode and 

### ISSUE THREAD

**Issue by Idaho947** [ImSorryButWho/HomeAssistantNotes#29]
Hello, 

I'm having trouble with the night mode. When it is activated, the "alarm off" mode is displayed (bleu logo) on the keypad. What happens if the alarm is triggered, after the reset delay, the panel continues to flash and doesn't switch off (since no alarm is triggered for it).

Is it possible to make the alarm mode also light up the away or present LED, so that it resets after the alarm delay?

**Comment by ImSorryButWho** [comment]
Based on #28 and this, I guess this is more common than I thought.  Obviously the designers at Ring built this keypad to support Home, Away and Disarmed.  How would you expect Night mode to map into this?

In particular, are you, like in #28, looking to just use Night instead of Home?  Do you use both?  If you push the Arm Home button, what state do you expect your alarm to go to?

**Comment by Idaho947** [comment]
Hello. I use night, home and away mode. In my opinion night is "a special mode" for home. So it can have the same beheavior no ?

**Comment by Idaho947** [comment]
Hello, any news about this change ?

**Comment by aaron-lts** [comment]
I'm sorry, I don't have the ability to do any testing on this at the moment.  If you want to put in a PR, I'll happily take a look.

**Comment by olibos** [comment]
Hello @Idaho947, I think my proposal in #36 might work for your situation as well.
Feel free to check it out and let me know what you think! 😊

**Comment by Idaho947** [comment]
sorry for the late reply... it's exactly that and the choice of volume according to night mode or not is a real plus!
