### ISSUE TITLE
Sensor Bypass Help

### ISSUE THREAD

**Issue by jasonwragg** [ImSorryButWho/HomeAssistantNotes#30]
I have some questions over the away bypass features.

When I enter my code and press away if there are open sensors should i get the bypass message straight away? Does it interrupt the countdown on the panel? 

My senario is, I set he alarm, there is a door open upstairs, the countdown on the alarm happens, then after leaving and the countdown finishes I get the notification that it failed to arm because of open sensor. Is that expected behaviour or have I not set something up incorrectly?

**Comment by ImSorryButWho** [comment]
Turn off "use exit delay" in Alarmo's advanced settings page for this sensor.  Since that's on, Alarmo thinks you're using that door to leave by.  Until the exit delay expires, it doesn't know anything is wrong. 

This isn't anything to do with the keypad.  All this blueprint is doing is accurately reflecting Alarmo's behavior.
